version: '3'

services:
  weba:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: docker-weba-container   
    ports:
      - "20001:5090" 
    expose:
      - "5090"
  webb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-webb-container   
    ports:
      - "20002:5090" 
    expose:
      - "5090"

  nginx:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    container_name: hasample_nginx
    ports:
      - "5000:80"
    links:
      - weba
      - webb